<?xml version="1.0" encoding="utf-8"?><Database Name="Miraclass" Class="MiraclassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-KLLGML0\SQLEXPRESS;Initial Catalog=Miraclass;Persist Security Info=True;User ID=sa" SettingsObjectName="Miraclass.Properties.Settings" SettingsPropertyName="MiraclassConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.S_User" Member="S_Users">
    <Type Name="S_User">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userFullName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isTeacher" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="S_User_P_Attendance" Member="P_Attendances" ThisKey="userId" OtherKey="userId" Type="P_Attendance" />
      <Association Name="S_User_P_Present" Member="P_Presents" ThisKey="userId" OtherKey="ownerId" Type="P_Present" />
      <Association Name="S_User_Q_question" Member="Q_questions" ThisKey="userId" OtherKey="userId" Type="Q_question" />
      <Association Name="S_User_N_savePresent" Member="N_savePresents" ThisKey="userId" OtherKey="userId" Type="N_savePresent" />
      <Association Name="S_User_N_Note" Member="N_Notes" ThisKey="userId" OtherKey="userId" Type="N_Note" />
    </Type>
  </Table>
  <Table Name="dbo.P_Attendance" Member="P_Attendances">
    <Type Name="P_Attendance">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="S_User_P_Attendance" Member="S_User" ThisKey="userId" OtherKey="userId" Type="S_User" IsForeignKey="true" />
      <Association Name="P_Room_P_Attendance" Member="P_Room" ThisKey="roomId" OtherKey="id" Type="P_Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.P_Room" Member="P_Rooms">
    <Type Name="P_Room">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoomName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoomDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="hostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="P_Room_P_Attendance" Member="P_Attendances" ThisKey="id" OtherKey="roomId" Type="P_Attendance" />
      <Association Name="P_Room_P_linkPresent" Member="P_linkPresents" ThisKey="id" OtherKey="roomId" Type="P_linkPresent" />
      <Association Name="P_Room_P_StatePresent" Member="P_StatePresents" ThisKey="id" OtherKey="roomId" Type="P_StatePresent" />
    </Type>
  </Table>
  <Table Name="dbo.P_Present" Member="P_Presents">
    <Type Name="P_Present">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="roomid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="cateId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ownerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="P_Present_P_linkPresent" Member="P_linkPresents" ThisKey="id" OtherKey="presentId" Type="P_linkPresent" />
      <Association Name="P_Present_P_StatePresent" Member="P_StatePresents" ThisKey="id" OtherKey="presentId" Type="P_StatePresent" />
      <Association Name="P_Present_N_savePresent" Member="N_savePresents" ThisKey="id" OtherKey="presentId" Type="N_savePresent" />
      <Association Name="P_Present_N_Note" Member="N_Notes" ThisKey="id" OtherKey="presentId" Type="N_Note" />
      <Association Name="S_User_P_Present" Member="S_User" ThisKey="ownerId" OtherKey="userId" Type="S_User" IsForeignKey="true" />
      <Association Name="P_data_P_Present" Member="P_data" ThisKey="id" OtherKey="id" Type="P_data" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.P_data" Member="P_datas">
    <Type Name="P_data">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="tempId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="P_data_P_Present" Member="P_Presents" ThisKey="id" OtherKey="id" Type="P_Present" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.P_linkPresent" Member="P_linkPresents">
    <Type Name="P_linkPresent">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="presentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="P_Present_P_linkPresent" Member="P_Present" ThisKey="presentId" OtherKey="id" Type="P_Present" IsForeignKey="true" />
      <Association Name="P_Room_P_linkPresent" Member="P_Room" ThisKey="roomId" OtherKey="id" Type="P_Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.P_StatePresent" Member="P_StatePresents">
    <Type Name="P_StatePresent">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="presentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roomId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="currentPage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="P_Present_P_StatePresent" Member="P_Present" ThisKey="presentId" OtherKey="id" Type="P_Present" IsForeignKey="true" />
      <Association Name="P_Room_P_StatePresent" Member="P_Room" ThisKey="roomId" OtherKey="id" Type="P_Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Q_Answer" Member="Q_Answers">
    <Type Name="Q_Answer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="questionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Q_question_Q_Answer" Member="Q_question" ThisKey="questionId" OtherKey="id" Type="Q_question" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Q_question" Member="Q_questions">
    <Type Name="Q_question">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="currentPage" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="presentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Q_question_Q_Answer" Member="Q_Answers" ThisKey="id" OtherKey="questionId" Type="Q_Answer" />
      <Association Name="S_User_Q_question" Member="S_User" ThisKey="userId" OtherKey="userId" Type="S_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.P_request" Member="P_requests">
    <Type Name="P_request">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="request" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.N_savePresent" Member="N_savePresents">
    <Type Name="N_savePresent">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="presentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="P_Present_N_savePresent" Member="P_Present" ThisKey="presentId" OtherKey="id" Type="P_Present" IsForeignKey="true" />
      <Association Name="S_User_N_savePresent" Member="S_User" ThisKey="userId" OtherKey="userId" Type="S_User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.N_Note" Member="N_Notes">
    <Type Name="N_Note">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="content" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="presentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="page" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="P_Present_N_Note" Member="P_Present" ThisKey="presentId" OtherKey="id" Type="P_Present" IsForeignKey="true" />
      <Association Name="S_User_N_Note" Member="S_User" ThisKey="userId" OtherKey="userId" Type="S_User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>