<?xml version="1.0" encoding="utf-8"?><Database Name="Miraclass" Class="MiraclassDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-KLLGML0\SQLEXPRESS;Initial Catalog=Miraclass;Persist Security Info=True;User ID=sa" SettingsObjectName="Miraclass.Properties.Settings" SettingsPropertyName="MiraclassConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.S_User" Member="S_Users">
    <Type Name="S_User">
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userPassword" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="userGroup" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="userFullName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="isActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="isTeacher" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="S_User_P_Attendance" Member="P_Attendances" ThisKey="userId" OtherKey="userId" Type="P_Attendance" />
    </Type>
  </Table>
  <Table Name="dbo.P_Room" Member="P_Rooms">
    <Type Name="P_Room">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoomName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RoomDesc" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="status" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="hostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="P_Room_P_Attendance" Member="P_Attendances" ThisKey="id" OtherKey="roomId" Type="P_Attendance" />
    </Type>
  </Table>
  <Table Name="dbo.P_Attendance" Member="P_Attendances">
    <Type Name="P_Attendance">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="userId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="roomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="P_Room_P_Attendance" Member="P_Room" ThisKey="roomId" OtherKey="id" Type="P_Room" IsForeignKey="true" />
      <Association Name="S_User_P_Attendance" Member="S_User" ThisKey="userId" OtherKey="userId" Type="S_User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>